// Généré : mapping avatar → jeu (validé). Tri par jeu puis personnage.
// Pour déplacer un avatar : changer son groupe ici.
export const AVATAR_GROUPS = [
  { game: "P1", key: "persona1", avatars: [
    "Eriko.png",
    "Hidehiko.png",
    "Hidehiko.webp",
    "Inaba.webp",
    "Inaba2.webp",
    "Kei.webp",
    "Kei2.jpg",
    "Naoya.jpg",
    "Naoya1.jpg",
    "Yuka.webp",
    "Yukino.webp",
  ] },
  { game: "P2", key: "persona2", avatars: [
    "Ekichi.jpeg",
    "Ekichi2.jpeg",
    "JOKER.webp",
    "Jun.jpg",
    "Lisa.jpeg",
    "Maya.jpg",
    "Maya2.jpeg",
    "Tatsuya.jpg",
    "Tatsuya2.jpg",
  ] },
  { game: "P3", key: "persona3", avatars: [
    // ── Les deux protagonistes de Persona 3, en tête et chacun d'un bloc ──────
    // Demande Hamza (2026-09-22) : Makoto puis Kotone, anciens et nouveaux
    // portraits mêlés. La galerie se parcourt à l'œil — un joueur cherche un
    // personnage, pas le lot qui a livré l'image.
    //
    // Deux exclusions volontaires, valables pour l'un comme pour l'autre :
    //   - `makoto_yuki_pq2.jpg` et `kotone_pq.jpg` restent dans le groupe PQ,
    //     qui est un roster COMPLET en style Persona Q (chaque personnage y a son
    //     entrée, de makoto_yuki_pq2 à crow_pq2). Les en sortir y ferait un trou.
    //   - `pfp_makoto.gif` et `Yuki_Zutomayo.jpeg` restent dans SPECIAL, qui
    //     regroupe les détournements et crossovers.
    //
    // Le crossover P5X × P3P de Kotone est ici et non dans le groupe P5X : c'est
    // elle qu'on cherche, pas le jeu où le dessin la place. Ses portraits ANIMÉS
    // ne sont pas ici non plus — ils forment le pack déblocable du lot 6, et seuls
    // les portraits libres vivent dans ce fichier.
    // Makoto Yuki
    "makoto_yuki.jpg",
    "Yuki.gif",
    "Yuki.jpeg",
    "yuki.jpg",
    "Yuki2.gif",
    // Kotone Shiomi
    "Kotone.jpeg",
    "Kotone2.jpeg",
    "Kotone3.jpeg",
    "kotone_pdp.jpg",
    "kotone_shiomi.jpg",
    "kotone_shiomi_p3p.jpg",
    "kotone_shiomi_p3p_2.jpg",
    "kotone_shiomi_p3p_3.jpg",
    "kotone_shiomi_p5x_crossover.jpg",
    // ─────────────────────────────────────────────────────────────────────────
    "aigis_train.jpg",
    "aigis.gif",
    "Aigis.jpg",
    "Aigis2.jpg",
    "Akihiko.jpg",
    "Chidori.jpg",
    "Chidori2.jpg",
    "Elisabeth.jpeg",
    "Elisabeth2.jpeg",
    "theodore.jpeg",
    "theodore2.jpeg",
    "theodore3.jpeg",
    "theodore4.jpeg",
    "theodore5.jpeg",
    "Fuuka.jpeg",
    "Fuuka2.jpeg",
    "Junpei.png",
    "Junpei2.jpg",
    "ken_amada_p4au.jpg",
    "Ken.jpeg",
    "Koromaru.jpg",
    "Koromaru2.jpg",
    "Metis.jpg",
    "Metis2.jpeg",
    "Mitsuru.jpg",
    "Mitsuru.webp",
    "Shinji.jpg",
    "Shinji.webp",
    "Yukari.jpg",
    "Yukari2.jpg",
  ] },
  { game: "P4", key: "persona4", avatars: [
    "Adachi.jpg",
    "Adachi2.jpeg",
    "chie_satonaka_icon.jpg",
    "Chie.jpg",
    "Chie2.jpg",
    "chiesatonaka_revivale.jpg",
    "Kanji.avif",
    "Kanji.jpg",
    "margaret.jpg",
    "Marie.jpg",
    "Marie2.webp",
    "Nanako.jpg",
    "Nanako2.jpg",
    "naoto_shirogane_icon_revivae.jpg",
    "Naoto.jpg",
    "Naoto2.jpg",
    "naotoshirogane.jpg",
    "rise_revivale.jpg",
    "Rise.jpg",
    "Rise.png",
    "Teddie.jpg",
    "Teddie2.jpg",
    "yosuke_hanamura_icon_1.jpg",
    "yosuke_hanamura_icon.jpg",
    "Yosuke.jpg",
    "Yosuke2.jpg",
    "yu_alt.jpg",
    "yu_cursed.jpg",
    "yu_narukami_mc_icon.jpg",
    "Yu.gif",
    "Yu.jpg",
    "Yu2.gif",
    "Yu2.jpg",
    "Yukiko.jpg",
    "Yukiko2.jpg",
    "hui_marie_p4r_pfp.jpg",
    "naoto_p4r.jpg",
    // Lot 2.3
    "rise_kujikawa_p4.jpg",
  ] },
  { game: "P5", key: "persona5", avatars: [
    "akechi_alt.jpg",
    "akechi_jazz.jpg",
    "Akechi.jpg",
    "Akechi2.jpg",
    "Ann_2.jpg",
    "ann_jazz.jpg",
    "Ann.jpg",
    "caroline_justine.png",
    "futaba_alt.jpg",
    "futaba_headphones.jpg",
    "futaba_persona5.jpg",
    "Futaba.jpg",
    "Futaba.webp",
    "Har.jpg",
    "haru_jazz.jpg",
    "Haru.png",
    "joker_starlight.jpg",
    "Joker.jpg",
    "Lavenza.jpg",
    "Lavenza7.gif",
    "makoto_nijima.jpg",
    "Makoto.jpg",
    "Makoto2.jpg",
    "makotoniijima_jazz.jpg",
    "Maruki.gif",
    "morgana_starlight.jpg",
    "Morgana.jpg",
    "Morgana.png",
    "ren_jazz.jpg",
    "ren_t.webp",
    "Ren.gif",
    "Ren.webp",
    "Ren2.gif",
    "ryuji_jazz.jpg",
    "Ryuji.jpg",
    "Ryuji.png",
    "sumire_jazz.jpg",
    "Sumire.jpg",
    "Sumire2.jpg",
    "Tae.jpg",
    "Tae2.jpg",
    "Yusuke.jpg",
    "Yusuke.webp",
    "yusukekitagawa_jazz.jpg",
    "morgana_dancing.jpg",
    // Lot 2.3 — Sophia vient de P5 Strikers, que ce groupe couvre déjà
    // (P5 / P5R / P5S), d'où sa place ici et non dans un groupe à part.
    "sophia_p5s.jpg",
  ] },
  { game: "P5X", key: "persona5x", avatars: [
    "Arai.png",
    "Arai2.png",
    "Kayo.png",
    "Kayo2.png",
    "luce.jpg",
    "Lufel.png",
    "Lufel2.png",
    "mionatsukawa_persona_5_phantom_x.jpg",
    "Riko.png",
    "Riko2.png",
    "seijishiratori_persona_5_phantom_x.jpg",
    "Shun.png",
    "Shun2.png",
    "Tomoko.png",
    "Tomoko2.png",
    "wonder_alt.jpg",
    "wonder_velvet.jpg",
    "Wonder.jpg",
    "wonder1.png",
    "wonder2.png",
    "Yaoling.png",
    "Yaoling2.png",
    "YUI.png",
    "YUI2.png",
    "yukimifujikawa_persona_5_phantom_x.jpg",
    // Lot 2.3 — Phantom Idols, skins, et le passage de Kotone Shiomi dans P5X.
    // Noms en snake_case (CLAUDE.md §4) : les fichiers livrés portaient des emoji,
    // des espaces multiples et des « (1) », que la liste blanche du serveur
    // (personadle_validate_avatar) refuse — un avatar refusé reste local et
    // disparaît au prochain pull cloud, sans le moindre message.
    "aran_hirano_p5x.jpg",
    "ayaka_sakai_p5x.jpg",
    "ayaka_sakai_p5x_2.jpg",
    "ayaka_sakai_p5x_3.jpg",
    "ayaka_sakai_p5x_4.jpg",
    "ayaka_sakai_summer_p5x.jpg",
    "hatsune_miku_p5x.jpg",
    "ichigo_shikano_p5x.jpg",
    "kira_kitazato_p5x.jpg",
    "kira_kitazato_p5x_2.jpg",
    "kira_kitazato_p5x_3.jpg",
    "kiyoshi_kurotani_p5x.jpg",
    // Kotone MONTAGNE (Mont) — une autre personne que Kotone Shiomi, malgré le
    // prénom commun. Elle reste ici, dans son jeu.
    "kotone_montagne_p5x.jpg",
    "kumi_katayama_p5x.jpg",
    "miyu_sahara_p5x.jpg",
    "narumi_nashimoto_p5x.jpg",
    "shoki_ikenami_p5x.jpg",
    "shoki_ikenami_notte_p5x.jpg",
    "wonder_joker_matching_p5x.jpg",
    "yaoling_li_p5x.jpg",
    "yui_comic_p5x.jpg",
    "yui_comic_p5x_2.jpg",
    "yumi_shiina_p5x.jpg",
    "yumi_shiina_p5x_2.jpg",
    "yumi_shiina_p5x_3.jpg",
  ] },
  // Persona Q / Q2 : les héros de P3, P4 et P5 dans leur habillage Etrian —
  // regroupés ici plutôt que dispersés dans le jeu d'origine de chaque personnage
  // (décision Hamza du 2026-09-18 : c'est le style qu'on cherche, pas le perso).
  { game: "PQ", key: "personaq", avatars: [
    "makoto_yuki_pq2.jpg",
    "kotone_pq.jpg",
    "yukari_pq2.jpg",
    "junpei_pq.jpg",
    "akihiko_pq2.jpg",
    "mitsuru_pq2.jpg",
    "aigis_pq2.jpg",
    "koromaru_pq2.jpg",
    "ken_amada_pq2.jpg",
    "shinjiro_pq2.jpg",
    "yu_pq.jpg",
    "yosuke_pq.jpg",
    "chie_pq.jpg",
    "yukiko_pq.jpg",
    "kanji_pq.jpg",
    "rise_pq.jpg",
    "teddie_pq.jpg",
    "naoto_pq.jpg",
    "joker_pq.jpg",
    "ryuji_pq.jpg",
    "ann_pq.jpg",
    "morgana_pq.jpg",
    "yusuke_pq.jpg",
    "makoto_nijima_pq.jpg",
    "haru_pq.jpg",
    "crow_pq2.jpg",
  ] },
  { game: "SPECIAL", key: "special", avatars: [
    "Anniversary.gif",
    "catlisabeth.gif",
    "jack_frost_gurren_aggan.jpg",
    "jack_frost_icon_persona.jpg",
    "jack_frost_peace_sign.jpg",
    "jack_frost.jpg",
    "luix-dextructor-aigis.gif",
    "meme_chie_shut_teddie.jpg",
    "pfp_makoto.gif",
    "Yuki_Zutomayo.jpeg",
    "jojo_frost.jpg",
  ] },
];
